package analyzers

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/kirankotari/ossguard-go/internal/detector"
)

// SLSARequirement represents a single SLSA provenance check.
type SLSARequirement struct {
	ID             string `json:"id"`
	Level          int    `json:"level"`
	Description    string `json:"description"`
	Status         string `json:"status"`
	Evidence       string `json:"evidence"`
	Recommendation string `json:"recommendation"`
}

// SLSAReport is the result of a SLSA provenance assessment.
type SLSAReport struct {
	Requirements  []SLSARequirement `json:"requirements"`
	AchievedLevel int               `json:"achieved_level"`
	MetCount      int               `json:"met_count"`
	TotalCount    int               `json:"total_count"`
	LevelLabel    string            `json:"level_label"`
}

type slsaDef struct {
	id    string
	level int
	desc  string
}

var slsaRequirements = []slsaDef{
	{"slsa-l1-provenance", 1, "Build process MUST generate provenance"},
	{"slsa-l1-ci", 1, "Build MUST run in a CI/CD system"},
	{"slsa-l1-published", 1, "Provenance MUST be available to consumers"},
	{"slsa-l2-hosted", 2, "Build MUST run on a hosted build service"},
	{"slsa-l2-signed", 2, "Provenance MUST be signed"},
	{"slsa-l2-service-gen", 2, "Provenance MUST be generated by the build service"},
	{"slsa-l3-isolated", 3, "Build MUST run in an isolated ephemeral environment"},
	{"slsa-l3-unforgeable", 3, "Provenance MUST be unforgeable"},
	{"slsa-l3-non-falsifiable", 3, "Build service MUST guarantee non-falsifiable provenance"},
	{"slsa-l4-hermetic", 4, "Build MUST be hermetic"},
	{"slsa-l4-reproducible", 4, "Build SHOULD be reproducible"},
	{"slsa-l4-two-party", 4, "All changes require two-party review"},
}

// CheckSLSA evaluates SLSA provenance levels for a project.
func CheckSLSA(projectPath string) *SLSAReport {
	abs, _ := filepath.Abs(projectPath)
	info := detector.DetectProject(abs)
	wfs := readWorkflows(abs)

	reqs := make([]SLSARequirement, 0, len(slsaRequirements))
	for _, sd := range slsaRequirements {
		s, e, r := checkSLSAReq(sd.id, abs, &info, wfs)
		reqs = append(reqs, SLSARequirement{ID: sd.id, Level: sd.level, Description: sd.desc, Status: s, Evidence: e, Recommendation: r})
	}

	met := 0
	for _, r := range reqs {
		if r.Status == "met" {
			met++
		}
	}
	achieved := 0
	for lvl := 1; lvl <= 4; lvl++ {
		all := true
		for _, r := range reqs {
			if r.Level == lvl && r.Status != "met" {
				all = false
				break
			}
		}
		if all {
			achieved = lvl
		} else {
			break
		}
	}
	label := "SLSA Level 0 (No provenance)"
	if achieved > 0 {
		label = "SLSA Build Level " + strings.Repeat("I", achieved)
		// use numeric
		switch achieved {
		case 1:
			label = "SLSA Build Level 1"
		case 2:
			label = "SLSA Build Level 2"
		case 3:
			label = "SLSA Build Level 3"
		case 4:
			label = "SLSA Build Level 4"
		}
	}
	return &SLSAReport{Requirements: reqs, AchievedLevel: achieved, MetCount: met, TotalCount: len(reqs), LevelLabel: label}
}

func checkSLSAReq(id, p string, info *detector.ProjectInfo, wfs []string) (string, string, string) {
	wfContains := func(kw string) bool {
		for _, c := range wfs {
			if strings.Contains(c, kw) {
				return true
			}
		}
		return false
	}

	switch id {
	case "slsa-l1-provenance":
		if wfContains("provenance") || wfContains("slsa") || wfContains("attest") || wfContains("in-toto") {
			return "met", "Provenance generation found in workflows", ""
		}
		return "unmet", "", "Add SLSA provenance generation (e.g. slsa-framework/slsa-github-generator)"
	case "slsa-l1-ci":
		if info.HasGithubActions {
			return "met", "GitHub Actions CI found", ""
		}
		for _, f := range []string{".travis.yml", ".circleci/config.yml", "Jenkinsfile", ".gitlab-ci.yml"} {
			if _, err := os.Stat(filepath.Join(p, f)); err == nil {
				return "met", "CI found", ""
			}
		}
		return "unmet", "", "Set up CI/CD — run `ossguard ci`"
	case "slsa-l1-published":
		if wfContains("upload-artifact") || wfContains("release") {
			return "met", "Artifacts published in CI", ""
		}
		return "unknown", "", "Publish provenance alongside release artifacts"
	case "slsa-l2-hosted":
		if info.HasGithubActions {
			return "met", "GitHub Actions is a hosted build service", ""
		}
		return "unknown", "", "Use a hosted CI service"
	case "slsa-l2-signed":
		if info.HasSigstore || wfContains("cosign") || wfContains("sigstore") || wfContains("attest") {
			return "met", "Signing configured", ""
		}
		return "unmet", "", "Sign provenance with Sigstore"
	case "slsa-l2-service-gen":
		if wfContains("slsa-github-generator") || wfContains("slsa-framework") {
			return "met", "SLSA generator produces provenance", ""
		}
		return "unmet", "", "Use slsa-framework/slsa-github-generator"
	case "slsa-l3-isolated":
		if info.HasGithubActions {
			return "met", "GitHub Actions runs on ephemeral VMs", ""
		}
		return "unknown", "", "Ensure builds run in isolated environments"
	case "slsa-l3-unforgeable":
		if wfContains("slsa-github-generator") {
			return "met", "SLSA generator produces unforgeable provenance", ""
		}
		return "unmet", "", "Use SLSA generator for unforgeable provenance"
	case "slsa-l3-non-falsifiable":
		if wfContains("slsa-github-generator") {
			return "met", "SLSA generator guarantees non-falsifiable provenance", ""
		}
		return "unmet", "", "Ensure provenance is generated outside the build job"
	case "slsa-l4-hermetic":
		return "unknown", "", "Verify builds are hermetic"
	case "slsa-l4-reproducible":
		return "unknown", "", "Verify builds are reproducible"
	case "slsa-l4-two-party":
		return "unknown", "", "Require two-party review for all changes"
	}
	return "unknown", "", ""
}
